[toolchain]
anchor_version = "0.30.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
express_relay = "26HRYgUNuW9zckjghRLzQuBfVoZtKhkVHfPRdYPZW3bz"
ez_lend = "D8WXCtJnRkGpGHHeHmUHAKsdtMEFRR7T5LqAXB4BzieS"
ez_lend_vanilla = "5UjkdSGokcs4HqkoZZs2Wv9HVgVW6ydeh9UVk953vM62"
kamino_lending = "3hoVgJh7XrZWyfTULgR8KkdS7PYgxhZnSbCsWGtYGgdb"
opportunity_adapter = "33SWSxyxVE8QbfE17xXeGZT7cphwTT6dEPeksqpedyH2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id_testing.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts --log-level log --kamino-elim-ixs initFarm"
