name: Build and Push Rust Services Image
on:
  push:
    branches:
      - debug/debug-dex-router
  workflow_dispatch:
    inputs:
      dispatch_description:
        description: "Dispatch description"
        required: true
        type: string
permissions:
  contents: read
  id-token: write
  packages: write
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  dex-router:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta_dex_router
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-dex-router
          tags: |
            type=sha,event=branch
            type=ref,event=tag
      - name: Build and push dex router docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ./scripts/dex-router
          push: true
          tags: ani-debug-dex-router
          labels: ${{ steps.meta_dex_router.outputs.labels }}
